---
- hosts: mac
  vars:
    pkgs:
      - htop
      - ranger
      - tig
      - tmux
      - tmuxinator
      - vim
      - zsh
    taps:
      - homebrew/cask
      - homebrew/cask-fonts
    casks:
      # amethyst and spectacl help with keyboard window arrangement.
      - amethyst
      - spectacle
      # RDM allows switching between screen resolution easily.
      - avibrazil-rdm
      # Popular browsers
      - firefox
      - google-chrome
      # GUI archiver
      - keka
      - vlc

    graphics:
      - handbrake
      - gimp
      - darktable

    ohmyzsh:
      theme: gnzh
      plugins:
        - ansible
        - brew
        - cask
        - colorize
        - cp
        - direnv
        - docker
        - docker-compose
        - docker-machine
        - fzf
        - git
        - git-extras
        - git-lfs
        - git-prompt
        - gitignore
        - golang
        - gradle
        - kubectl
        - osx
        - tig
        - tmux
        - tmuxinator
        - vagrant
        - vagrant-prompt

  tasks:
    - name: Install base packages
      community.general.homebrew:
        name: "{{ pkgs }}"
        state: present
        update_homebrew: yes

    - name: Register taps
      community.general.homebrew_tap:
        name: "{{ item }}"
        state: present
      with_items: "{{ taps }}"

    - name: Install casks
      community.general.homebrew_cask:
        name: "{{ casks }}"
        state: present

    - name: Make zsh the default shell
      become: yes
      user:
        name: "{{ ansible_user_id }}"
        shell: "/usr/local/bin/zsh"

    - name: Install OhMyZsh
      block:
        - name: Clone oh-my-zsh repo
          git:
            repo: https://github.com/ohmyzsh/ohmyzsh.git
            dest: "~/.oh-my-zsh"
        - name: Deploy .zshrc
          template:
            src: .zshrc.j2
            dest: "~/.zshrc"

    - name: Set sane defaults for mac
      import_role:
        name: lafarer.osx-defaults
      vars:
        target_user_id: "{{ ansible_user_id }}"
        # Configure_Keyboard: yes
        Configure_Finder: yes
        Configure_Bluetooth: yes
        Configure_Dock: yes
        # Configure_Trackpad: yes

        Bluetooth_ShowInMenuBar: yes
        Dock_Autohide: yes
        Dock_ShowProcessIndicators: yes
        Dock_MinEffect: "genie"
        Finder_ShowExternalHardDrivesOnDesktop: yes
        Finder_ShowRemovableMediaOnDesktop: yes
        Finder_AppleShowAllExtensions: yes
        Finder_AppleShowAllFiles: yes
        Finder_ShowStatusBar: yes
        # Role is broken for these domains.
        # Keyboard_KeyRepeat: 0
        # Keyboard_InitialKeyRepeat: 10
        # Keyboard_AutomaticSpellingCorrectionEnabled: yes
        # Trackpad_Clicking: Enabled
        # Trackpad_Dragging: Enabled
        # Trackpad_TrackpadHandResting: Enabled
        # Trackpad_TrackpadRightClick: Enabled
        # Trackpad_TrackpadScroll: Enabled

    - name: Fix settings manually
      osx_defaults:
        domain: "{{ item.domain }}"
        key: "[{ item.key }}"
        type: "{{ item.type }}"
        value: "{{ item.value }}"
      loop:
        - domain: NSGlobalDomain
          key: InitialKeyRepeat
          type: int
          value: 10
        - domain: NSGlobalDomain
          key: KeyRepeat
          type: int
          value: 10
        - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
          key: Clicking
          type: int
          value: 1
        - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
          key: Dragging
          type: int
          value: 0
        - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
          key: TrackpadRightClick
          type: int
          value: 1
        - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
          key: TrackpadScroll
          type: int
          value: 1
        - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
          key: TrackpadHandResting
          type: int
          value: 1
