---
- hosts: mac
  gather_facts: yes

- import_playbook: base.yml
- import_playbook: vim.yml
- import_playbook: base-gui.yml
- import_playbook: mac-settings.yml
- import_playbook: development.yml
- import_playbook: development-gui.yml
